### PR TITLE
Minimalistic API kube-node proposal

### PR DESCRIPTION
**Pull request by scheeles**
This is a proposal forkube-node is a minimalistic API which enables Kubernetes to manage its nodes by itself.

@adieu @sttts @ledzep2 @mrIncompetent please add you comments

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Fine from my side

**Comment by adieu** [comment]
LGTM. Let's bring the kube-node idea to broader audience.

**Comment by ledzep2** [comment]
LGTM.

**Pull request merged**
